root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Build the server inside ./cmd/server, NOT the module root
  cmd = "go build -o ./tmp/main.exe ./cmd/server"
  bin = "tmp\\main.exe"

  delay = 1000
  rerun = false
  rerun_delay = 500

  # Watch only useful dirs (faster). Add/remove as needed.
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html"]

  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  exclude_file = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  args_bin = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
