version: '3.8'

services:
  vessel-telemetry:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vessel-telemetry-api-prod
    ports:
      - "31180:31180"
    environment:
      - PORT=31180
      - DB_PATH=/app/data/telemetry.db
      - ALLOW_UNSAFE_DUPLICATE_INGEST=false
    volumes:
      # Use named volume for production data persistence
      - vessel-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31180/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vessel-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: vessel-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      vessel-telemetry:
        condition: service_healthy
    restart: always
    networks:
      - vessel-network

networks:
  vessel-network:
    driver: bridge

volumes:
  vessel-data:
    driver: local